require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'app/helpers/application_helper.rb'

Metrics/AbcSize:
  Exclude:
    - 'app/controllers/users/*'

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/users/*'

Style/FrozenStringLiteralComment:
  Enabled: false